subjects:
- data_path: './data/HC/sub-01/denoised_data.nii.gz'
  events_path: './data/HC/sub-01/sub-01_timing.txt'
  tr: 1.0
  numpy_path: './numpy_data/HC/sub-01.npy'

- data_path: './data/HC/sub-02/denoised_data.nii.gz'
  events_path: './data/HC/sub-02/sub-02_timing.txt'
  tr: 1.0
  numpy_path: './numpy_data/HC/sub-02.npy'

- data_path: './data/HC/sub-03/denoised_data.nii.gz'
  events_path: './data/HC/sub-03/sub-03_timing.txt'
  tr: 1.0
  numpy_path: './numpy_data/HC/sub-03.npy'

- data_path: './data/HC/sub-04/denoised_data.nii.gz'
  events_path: './data/HC/sub-04/sub-04_timing.txt'
  tr: 1.0
  numpy_path: './numpy_data/HC/sub-04.npy'  

- data_path: './data/HC/sub-05/denoised_data.nii.gz'
  events_path: './data/HC/sub-05/sub-05_timing.txt'
  tr: 1.0  
  numpy_path: './numpy_data/HC/sub-05.npy' 
    
- data_path: './data/HC/sub-06/denoised_data.nii.gz'
  events_path: './data/HC/sub-06/sub-06_timing.txt'
  tr: 1.0
  numpy_path: './numpy_data/HC/sub-06.npy'    

- data_path: './data/HC/sub-07/denoised_data.nii.gz'
  events_path: './data/HC/sub-07/sub-07_timing.txt'
  tr: 1.0
  numpy_path: './numpy_data/HC/sub-07.npy'    

- data_path: './data/HC/sub-08/denoised_data.nii.gz'
  events_path: './data/HC/sub-08/sub-08_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-08.npy'    

- data_path: './data/HC/sub-09/denoised_data.nii.gz'
  events_path: './data/HC/sub-09/sub-09_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-09.npy'    

- data_path: './data/HC/sub-10/denoised_data.nii.gz'
  events_path: './data/HC/sub-10/sub-10_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-10.npy'

- data_path: './data/HC/sub-11/denoised_data.nii.gz'
  events_path: './data/HC/sub-11/sub-11_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-11.npy'    

- data_path: './data/HC/sub-12/denoised_data.nii.gz'
  events_path: './data/HC/sub-12/sub-12_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-12.npy'

- data_path: './data/HC/sub-13/denoised_data.nii.gz'
  events_path: './data/HC/sub-13/sub-13_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-13.npy'

- data_path: './data/HC/sub-14/denoised_data.nii.gz'
  events_path: './data/HC/sub-14/sub-14_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-14.npy'

- data_path: './data/HC/sub-15/denoised_data.nii.gz'
  events_path: './data/HC/sub-15/sub-15_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-15.npy'

- data_path: './data/HC/sub-16/denoised_data.nii.gz'
  events_path: './data/HC/sub-16/sub-16_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-16.npy'

- data_path: './data/HC/sub-17/denoised_data.nii.gz'
  events_path: './data/HC/sub-17/sub-17_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-17.npy'

- data_path: './data/HC/sub-18/denoised_data.nii.gz'
  events_path: './data/HC/sub-18/sub-18_timing.txt'
  tr: 1.11
  numpy_path: './numpy_data/HC/sub-18.npy'