atlas_path: "./atlas/atlas_resample.nii"
train_model: false
model_path: "./models/test_model"
save_to_numpy: false
func: "max"
features_type: "ranks_five"
results_path: "./results.txt"
training_dataset:
- data_path: /home/aaanpilov/diploma/project/data/test_data/1374_Stolbov_A_P/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1374_Stolbov_A_P/1374
    Столбов имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1374_Stolbov_A_P.npy
- data_path: /home/aaanpilov/diploma/project/data/test_data/1386_Pitersky_A_Yu/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1386_Pitersky_A_Yu/1386
    Питерский имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1386_Pitersky_A_Yu.npy
- data_path: /home/aaanpilov/diploma/project/data/test_data/1387_Shumov_A_D/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1387_Shumov_A_D/1387
    Шумов имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1387_Shumov_A_D.npy
- data_path: /home/aaanpilov/diploma/project/data/test_data/1392_Bushlakin_R_O/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1392_Bushlakin_R_O/1392
    Бушлакин имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1392_Bushlakin_R_O.npy
- data_path: /home/aaanpilov/diploma/project/data/test_data/1393_Rogachev_S_I/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1393_Rogachev_S_I/1393
    Рогачёв имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1393_Rogachev_S_I.npy
- data_path: /home/aaanpilov/diploma/project/data/test_data/1394_Bunin_D_L/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1394_Bunin_D_L/1394
    Бунин имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1394_Bunin_D_L.npy
- data_path: /home/aaanpilov/diploma/project/data/test_data/1396_Egorov_A_V/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1396_Egorov_A_V/1396
    Егоров имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1396_Egorov_A_V.npy
- data_path: /home/aaanpilov/diploma/project/data/test_data/1397_Korolev_B_S/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1397_Korolev_B_S/1397
    Королев имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1397_Korolev_B_S.npy
- data_path: /home/aaanpilov/diploma/project/data/test_data/1398_Kovalevsky_A_E/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1398_Kovalevsky_A_E/1398
    Ковалевский имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1398_Kovalevsky_A_E.npy
- data_path: /home/aaanpilov/diploma/project/data/test_data/1418_Egorov_N_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/test_data/1418_Egorov_N_A/1418
    Егоров имя нет.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_test_data/1418_Egorov_N_A.npy

test_dataset:
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1136_DOROSHENKO_N_I__1136/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1136_DOROSHENKO_N_I__1136/Дорошенко
    имя.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1136_DOROSHENKO_N_I__1136.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1146_KRYLOV_V_O__1146/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1146_KRYLOV_V_O__1146/Крылов
    имя.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1146_KRYLOV_V_O__1146.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1152_BAKAEV_A_T__1152/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1152_BAKAEV_A_T__1152/Бакаев
    имя.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1152_BAKAEV_A_T__1152.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1153_ZYZYKIN_A_P__1153/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1153_ZYZYKIN_A_P__1153/ЗызыкинА
    имя.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1153_ZYZYKIN_A_P__1153.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1168_NESTER_A_O__1168/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1168_NESTER_A_O__1168/Нестер
    имя.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1168_NESTER_A_O__1168.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1186_MAGOMEDOV_A_A__1186/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1186_MAGOMEDOV_A_A__1186/Магомедов
    имя нет.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1186_MAGOMEDOV_A_A__1186.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1329_Lisitsin_I_S/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1329_Lisitsin_I_S/1329
    Лисицин имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1329_Lisitsin_I_S.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1339_Berdikov_P_G/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1339_Berdikov_P_G/1339
    Бердиков имя + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1339_Berdikov_P_G.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1342_Mozgovoi_V_V/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1342_Mozgovoi_V_V/1342
    Мозговой имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1342_Mozgovoi_V_V.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1350_Matveev_M_I/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1350_Matveev_M_I/1350
    Матвеев имя нет+ счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1350_Matveev_M_I.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1351_Kruglov_V_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1351_Kruglov_V_A/1351
    Круглов имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1351_Kruglov_V_A.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1352_Zemkin_V_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1352_Zemkin_V_A/1352 Земкин
    имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1352_Zemkin_V_A.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1357_Kozhanov_K_D/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1357_Kozhanov_K_D/1357
    Кожанов имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1357_Kozhanov_K_D.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1364_Nabiev_T_R/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1364_Nabiev_T_R/1364 Набиев
    имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1364_Nabiev_T_R.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1365_Dolgikh_S_V/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1365_Dolgikh_S_V/1365
    Долгих имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1365_Dolgikh_S_V.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1366_Dyatlov_G_I/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1366_Dyatlov_G_I/1366
    Дятлов имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1366_Dyatlov_G_I.npy
- data_path: /home/aaanpilov/diploma/project/data/hc_data/1373_Russak_D_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/hc_data/1373_Russak_D_A/1373 Руссак
    имя нет + счёт.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_hc_data/1373_Russak_D_A.npy
