subjects:
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1154_TYULGANOVA_D_A__1154/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1154_TYULGANOVA_D_A__1154/Тюльганова
    имя.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1154_TYULGANOVA_D_A__1154.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1158_POCHENCHUK_K_A__1158/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1158_POCHENCHUK_K_A__1158/Поченчук
    имя нет.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1158_POCHENCHUK_K_A__1158.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1165_Kolykhalova_K_O/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1165_Kolykhalova_K_O/Колыхалова
    имя нет.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1165_Kolykhalova_K_O.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1173_Bartashev_A_S/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1173_Bartashev_A_S/Барташев
    имя да-нет.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1173_Bartashev_A_S.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1177_Ivanov_S_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1177_Ivanov_S_A/Иванов имя
    да-нет.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1177_Ivanov_S_A.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1178_Finogenov_A_V/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1178_Finogenov_A_V/Финогенов
    имя нет.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1178_Finogenov_A_V.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1184_Linichenko_A_G/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1184_Linichenko_A_G/Линиченко
    имя нет.txt
  tr: 1.0
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1184_Linichenko_A_G.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1193_Ulyanova_E_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1193_Ulyanova_E_A/Ульянова
    имя нет.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1193_Ulyanova_E_A.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1202_Shtamburg_N_S/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1202_Shtamburg_N_S/Штамбург
    имя нет.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1202_Shtamburg_N_S.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1206_Buynitsky_D_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1206_Buynitsky_D_A/Буйницкий
    имя нет.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1206_Buynitsky_D_A.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1220_Ibragimova_K_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1220_Ibragimova_K_A/ИбрагимоваК
    имя нет.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1220_Ibragimova_K_A.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1221_Ibragimova_V_Kh/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1221_Ibragimova_V_Kh/ИбрагимоваВ
    имя нет.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1221_Ibragimova_V_Kh.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1227_Gavrilov_A_M/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1227_Gavrilov_A_M/Гаврилов
    имя нет.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1227_Gavrilov_A_M.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1234_Kuzin_M_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1234_Kuzin_M_A/Кузин имя
    нет.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1234_Kuzin_M_A.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1506_Nikishova_Anna/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1506_Nikishova_Anna/2021-5-13-11h-20m-19s.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1506_Nikishova_Anna.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1507_Tkach_A_M/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1507_Tkach_A_M/2021-5-20-14h-46m-34s.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1507_Tkach_A_M.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1508_Shostak_A_A/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1508_Shostak_A_A/2021-5-25-10h-54m-42s.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1508_Shostak_A_A.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1509_Bogomolova_M_M/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1509_Bogomolova_M_M/2021-5-27-11h-53m-46s.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1509_Bogomolova_M_M.npy
- data_path: /home/aaanpilov/diploma/project/data/SCHZ/1510_Foltsov_P_I/sdenoised_data.nii.gz
  events_path: /home/aaanpilov/diploma/project/data/SCHZ/1510_Foltsov_P_I/2021-6-1-11h-1m-5s.txt
  tr: 1.11
  numpy_path: /home/aaanpilov/diploma/project/numpy_data/raw_schz/1510_Foltsov_P_I.npy
